### ISSUE TITLE
junit report cannot be parsed by teamcity if assertion message has curly brackets

### ISSUE THREAD

**Issue by baksale** [testmyorgdotcom/deploy-test-status#1]
This is the line generated:
`<testcase name="testMethod" classname="testClass" time="0.123"><failure message="System.AssertException: Assertion Failed: Expected: {"a":null,"b":null,"c":null}, Actual: {"a":null,"b":null,"c":null,"d":null}"><![CDATA[Class.testClass.testMethod: line 123, column 1]]></failure></testcase>`
most likely due to curly brackets

**Comment by danilishe** [comment]
I will fix that one )

**Comment by baksale** [comment]
the issue was due to double quotes inside attribute value (separators have to be encoded inside attribute values)
